service: cart-api-2

frameworkVersion: '3'

useDotenv: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  region: ca-central-1
  environment:
    DB_HOST: ${env.DB_HOST}
    DB_PORT: ${env.DB_PORT}
    DB_USERNAME: ${env.DB_USERNAME}
    DB_PASSWORD: ${env.DB_PASSWORD}

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'